package request

var tokenURLRoot = "https://c2.yonyoucloud.com/iuap-api-auth"
var tokenURL = tokenURLRoot + "/open-auth/selfAppAuth/getAccessToken"

var URLRoot = "https://c2.yonyoucloud.com/iuap-api-gateway"

// digitalModel
var CurrencyListURL = URLRoot + "/yonbip/digitalModel/currency/list"
var CurrencyDetailURL = URLRoot + "/yonbip/digitalModel/currency/detail"
var MerchantListURL = URLRoot + "/yonbip/digitalModel/merchant/list"
var MerchantDetailURL = URLRoot + "/yonbip/digitalModel/merchant/detail"
var AdminDeptTreeURL = URLRoot + "/yonbip/digitalModel/admindept/tree"
var ExchangeRateTypeListURL = URLRoot + "/yonbip/digitalModel/exchangeratetype/list"
var ExchangeRateListURL = URLRoot + "/yonbip/digitalModel/exchangerate/list"
var OrgUnitTreeURL = URLRoot + "/yonbip/digitalModel/orgunit/querytree"
var ProductListURL = URLRoot + "/yonbip/digitalModel/product/list"
var ProductDetailURL = URLRoot + "/yonbip/digitalModel/product/detail"
var StaffListURL = URLRoot + "/yonbip/digitalModel/staff/list"
var StaffDetailURL = URLRoot + "/yonbip/digitalModel/staff/detail"
var TransactionListURL = URLRoot + "/yonbip/digitalModel/transtype/list"
var TransactionTreeURL = URLRoot + "/yonbip/digitalModel/transtype/tree"
var WarehouseListURL = URLRoot + "/yonbip/digitalModel/warehouse/list"
var WarehouseDetailURL = URLRoot + "/yonbip/digitalModel/warehouse/detail"
var GoodsPositionTree = URLRoot + "/yonbip/digitalModel/goodsposition/tree"
var GoodsProductSKUProList = URLRoot + "/yonbip/digitalModel/goodsproductskupro/list"

// scm
var OthInRecordListURL = URLRoot + "/yonbip/scm/othinrecord/list"
var OthInRecordDetailURL = URLRoot + "/yonbip/scm/othinrecord/detail"
var OthOutRecordListURL = URLRoot + "/yonbip/scm/othoutrecord/list"
var OthOutRecordDetailURL = URLRoot + "/yonbip/scm/othoutrecord/detail"
var PurInRecordListURL = URLRoot + "/yonbip/scm/purinrecord/list"
var PurInRecordDetailURL = URLRoot + "/yonbip/scm/purinrecord/detail"
var SalesOutListURL = URLRoot + "/yonbip/scm/salesout/list"
var SalesOutDetailURL = URLRoot + "/yonbip/scm/salesout/detail"
var SNFlowDirectionListURL = URLRoot + "/yonbip/scm/snflowdirection/list"
var SNQuerySNStateListURL = URLRoot + "/yonbip/scm/snQuerysnstate/list"
var QueryCurrentStocksByConditionURL = URLRoot + "/yonbip/scm/stock/QueryCurrentStocksByCondition"
var TransferApplySaveURL = URLRoot + "/yonbip/scm/transferapply/save"
var TransferApplyBatchAuditURL = URLRoot + "/yonbip/scm/transferapply/batchaudit"
var TransferApplyListURL = URLRoot + "/yonbip/scm/transferapply/list"
var TransferReqSaveURL = URLRoot + "/yonbip/scm/transferreq/save"
var TransferReqBatchAuditURL = URLRoot + "/yonbip/scm/transferreq/batchaudit"
var TransferReqListURL = URLRoot + "/yonbip/scm/transferreq/list"
var MorphologyConversionSaveURL = URLRoot + "/yonbip/scm/morphologyconversion/save"
var MorphologyConversionBatchAuditURL = URLRoot + "/yonbip/scm/morphologyconversion/batchaudit"
var StoreOutListURL = URLRoot + "/yonbip/scm/storeout/list"
var StoreOutDetailURL = URLRoot + "/yonbip/scm/storeout/detail"
var StoreInListURL = URLRoot + "/yonbip/scm/storein/list"
var StoreInDetailURL = URLRoot + "/yonbip/scm/storein/detail"
var StoreTransferListURL = URLRoot + "/yonbip/scm/storetransfer/list"
var LocationStockAnalysisList = URLRoot + "/yonbip/scm/locationstockanalysis/list"
var StockAnalysisList = URLRoot + "/yonbip/scm/stockanalysis/list"

// sd
var MerchantProductPriceURL = URLRoot + "/yonbip/sd/goods/price/customerproduct/list"
var VoucherOrderListURL = URLRoot + "/yonbip/sd/voucherorder/list"
var VoucherOrderDetailURL = URLRoot + "/yonbip/sd/voucherorder/detail"
var VoucherOrderSaveURL = URLRoot + "/yonbip/sd/voucherorder/save"
var VoucherOrderBatchAuditURL = URLRoot + "/yonbip/sd/voucherorder/batchaudit"
var VoucherOrderCloseURL = URLRoot + "/yonbip/sd/voucherorder/close"
var VoucherSaleReturnListURL = URLRoot + "/yonbip/sd/vouchersalereturn/list"
var VoucherSaleReturnDetailURL = URLRoot + "/yonbip/sd/vouchersalereturn/detail"
var VoucherDeliveryListURL = URLRoot + "/yonbip/sd/voucherdelivery/list"
var VoucherDeliveryUnauditURL = URLRoot + "/yonbip/sd/voucherdelivery/unaudit"
var VoucherDeliveryBatchDeleteURL = URLRoot + "/yonbip/sd/voucherdelivery/batchdelete"

// dst
var TradeVouchImportURL = URLRoot + "/yonbip/sd/dst/tradevouch/import"
var TradeVouchQueryURL = URLRoot + "/yonbip/sd/dst/tradevouch/query"
var SuitGoodsQueryURL = URLRoot + "/yonbip/sd/dst/suitgoods/query"
var TradeOrderQueryURL = URLRoot + "/yonbip/sd/dst/tradeorder/query"
var TradeOrderHoldURL = URLRoot + "/yonbip/sd/dst/tradeorder/tradehold"

func refreshURLs() {
	tokenURL = tokenURLRoot + "/open-auth/selfAppAuth/getAccessToken"

	// digitalModel
	CurrencyListURL = URLRoot + "/yonbip/digitalModel/currency/list"
	CurrencyDetailURL = URLRoot + "/yonbip/digitalModel/currency/detail"
	MerchantListURL = URLRoot + "/yonbip/digitalModel/merchant/list"
	MerchantDetailURL = URLRoot + "/yonbip/digitalModel/merchant/detail"
	AdminDeptTreeURL = URLRoot + "/yonbip/digitalModel/admindept/tree"
	ExchangeRateTypeListURL = URLRoot + "/yonbip/digitalModel/exchangeratetype/list"
	ExchangeRateListURL = URLRoot + "/yonbip/digitalModel/exchangerate/list"
	OrgUnitTreeURL = URLRoot + "/yonbip/digitalModel/orgunit/querytree"
	ProductListURL = URLRoot + "/yonbip/digitalModel/product/list"
	ProductDetailURL = URLRoot + "/yonbip/digitalModel/product/detail"
	StaffListURL = URLRoot + "/yonbip/digitalModel/staff/list"
	StaffDetailURL = URLRoot + "/yonbip/digitalModel/staff/detail"
	TransactionListURL = URLRoot + "/yonbip/digitalModel/transtype/list"
	TransactionTreeURL = URLRoot + "/yonbip/digitalModel/transtype/tree"
	WarehouseListURL = URLRoot + "/yonbip/digitalModel/warehouse/list"
	WarehouseDetailURL = URLRoot + "/yonbip/digitalModel/warehouse/detail"
	GoodsPositionTree = URLRoot + "/yonbip/digitalModel/goodsposition/tree"
	GoodsProductSKUProList = URLRoot + "/yonbip/digitalModel/goodsproductskupro/list"

	// scm
	OthInRecordListURL = URLRoot + "/yonbip/scm/othinrecord/list"
	OthInRecordDetailURL = URLRoot + "/yonbip/scm/othinrecord/detail"
	OthOutRecordListURL = URLRoot + "/yonbip/scm/othoutrecord/list"
	OthOutRecordDetailURL = URLRoot + "/yonbip/scm/othoutrecord/detail"
	PurInRecordListURL = URLRoot + "/yonbip/scm/purinrecord/list"
	PurInRecordDetailURL = URLRoot + "/yonbip/scm/purinrecord/detail"
	SalesOutListURL = URLRoot + "/yonbip/scm/salesout/list"
	SalesOutDetailURL = URLRoot + "/yonbip/scm/salesout/detail"
	SNFlowDirectionListURL = URLRoot + "/yonbip/scm/snflowdirection/list"
	SNQuerySNStateListURL = URLRoot + "/yonbip/scm/snQuerysnstate/list"
	QueryCurrentStocksByConditionURL = URLRoot + "/yonbip/scm/stock/QueryCurrentStocksByCondition"
	TransferApplySaveURL = URLRoot + "/yonbip/scm/transferapply/save"
	TransferApplyBatchAuditURL = URLRoot + "/yonbip/scm/transferapply/batchaudit"
	TransferApplyListURL = URLRoot + "/yonbip/scm/transferapply/list"
	TransferReqSaveURL = URLRoot + "/yonbip/scm/transferreq/save"
	TransferReqBatchAuditURL = URLRoot + "/yonbip/scm/transferreq/batchaudit"
	TransferReqListURL = URLRoot + "/yonbip/scm/transferreq/list"
	MorphologyConversionSaveURL = URLRoot + "/yonbip/scm/morphologyconversion/save"
	MorphologyConversionBatchAuditURL = URLRoot + "/yonbip/scm/morphologyconversion/batchaudit"
	StoreOutListURL = URLRoot + "/yonbip/scm/storeout/list"
	StoreOutDetailURL = URLRoot + "/yonbip/scm/storeout/detail"
	StoreInListURL = URLRoot + "/yonbip/scm/storein/list"
	StoreInDetailURL = URLRoot + "/yonbip/scm/storein/detail"
	StoreTransferListURL = URLRoot + "/yonbip/scm/storetransfer/list"
	LocationStockAnalysisList = URLRoot + "/yonbip/scm/locationstockanalysis/list"
	StockAnalysisList = URLRoot + "/yonbip/scm/stockanalysis/list"

	// sd
	MerchantProductPriceURL = URLRoot + "/yonbip/sd/goods/price/customerproduct/list"
	VoucherOrderListURL = URLRoot + "/yonbip/sd/voucherorder/list"
	VoucherOrderDetailURL = URLRoot + "/yonbip/sd/voucherorder/detail"
	VoucherOrderSaveURL = URLRoot + "/yonbip/sd/voucherorder/save"
	VoucherOrderBatchAuditURL = URLRoot + "/yonbip/sd/voucherorder/batchaudit"
	VoucherOrderCloseURL = URLRoot + "/yonbip/sd/voucherorder/close"
	VoucherSaleReturnListURL = URLRoot + "/yonbip/sd/vouchersalereturn/list"
	VoucherSaleReturnDetailURL = URLRoot + "/yonbip/sd/vouchersalereturn/detail"
	VoucherDeliveryListURL = URLRoot + "/yonbip/sd/voucherdelivery/list"
	VoucherDeliveryUnauditURL = URLRoot + "/yonbip/sd/voucherdelivery/unaudit"
	VoucherDeliveryBatchDeleteURL = URLRoot + "/yonbip/sd/voucherdelivery/batchdelete"

	// dst
	TradeVouchImportURL = URLRoot + "/yonbip/sd/dst/tradevouch/import"
	TradeVouchQueryURL = URLRoot + "/yonbip/sd/dst/tradevouch/query"
	SuitGoodsQueryURL = URLRoot + "/yonbip/sd/dst/suitgoods/query"
	TradeOrderQueryURL = URLRoot + "/yonbip/sd/dst/tradeorder/query"
	TradeOrderHoldURL = URLRoot + "/yonbip/sd/dst/tradeorder/tradehold"
}
