package request

var tokenURLRoot = "https://open.yonyoucloud.com"
var tokenURL = tokenURLRoot + "/open-auth/selfAppAuth/getAccessToken"

var urlRoot = "https://yonbip.diwork.com/iuap-api-gateway"
var URLRoot = urlRoot

// digitalModel
var CurrencyListURL = urlRoot + "/yonbip/digitalModel/currency/list"
var CurrencyDetailURL = urlRoot + "/yonbip/digitalModel/currency/detail"
var MerchantListURL = urlRoot + "/yonbip/digitalModel/merchant/list"
var MerchantDetailURL = urlRoot + "/yonbip/digitalModel/merchant/detail"
var AdminDeptTreeURL = urlRoot + "/yonbip/digitalModel/admindept/tree"
var ExchangeRateTypeListURL = urlRoot + "/yonbip/digitalModel/exchangeratetype/list"
var ExchangeRateListURL = urlRoot + "/yonbip/digitalModel/exchangerate/list"
var OrgUnitTreeURL = urlRoot + "/yonbip/digitalModel/orgunit/querytree"
var ProductListURL = urlRoot + "/yonbip/digitalModel/product/list"
var ProductDetailURL = urlRoot + "/yonbip/digitalModel/product/detail"
var StaffListURL = urlRoot + "/yonbip/digitalModel/staff/list"
var StaffDetailURL = urlRoot + "/yonbip/digitalModel/staff/detail"
var TransactionListURL = urlRoot + "/yonbip/digitalModel/transtype/list"
var TransactionTreeURL = urlRoot + "/yonbip/digitalModel/transtype/tree"
var WarehouseListURL = urlRoot + "/yonbip/digitalModel/warehouse/list"
var WarehouseDetailURL = urlRoot + "/yonbip/digitalModel/warehouse/detail"
var GoodsPositionTree = urlRoot + "/yonbip/digitalModel/goodsposition/tree"
var GoodsProductSKUProList = urlRoot + "/yonbip/digitalModel/goodsproductskupro/list"

// scm
var OthInRecordListURL = urlRoot + "/yonbip/scm/othinrecord/list"
var OthInRecordDetailURL = urlRoot + "/yonbip/scm/othinrecord/detail"
var OthOutRecordListURL = urlRoot + "/yonbip/scm/othoutrecord/list"
var OthOutRecordDetailURL = urlRoot + "/yonbip/scm/othoutrecord/detail"
var PurInRecordListURL = urlRoot + "/yonbip/scm/purinrecord/list"
var PurInRecordDetailURL = urlRoot + "/yonbip/scm/purinrecord/detail"
var SalesOutListURL = urlRoot + "/yonbip/scm/salesout/list"
var SalesOutDetailURL = urlRoot + "/yonbip/scm/salesout/detail"
var SNFlowDirectionListURL = urlRoot + "/yonbip/scm/snflowdirection/list"
var SNQuerySNStateListURL = urlRoot + "/yonbip/scm/snQuerysnstate/list"
var QueryCurrentStocksByConditionURL = urlRoot + "/yonbip/scm/stock/QueryCurrentStocksByCondition"
var TransferApplySaveURL = urlRoot + "/yonbip/scm/transferapply/save"
var TransferApplyBatchAuditURL = urlRoot + "/yonbip/scm/transferapply/batchaudit"
var TransferApplyListURL = urlRoot + "/yonbip/scm/transferapply/list"
var TransferReqSaveURL = urlRoot + "/yonbip/scm/transferreq/save"
var TransferReqBatchAuditURL = urlRoot + "/yonbip/scm/transferreq/batchaudit"
var TransferReqListURL = urlRoot + "/yonbip/scm/transferreq/list"
var MorphologyConversionSaveURL = urlRoot + "/yonbip/scm/morphologyconversion/save"
var MorphologyConversionBatchAuditURL = urlRoot + "/yonbip/scm/morphologyconversion/batchaudit"
var StoreOutListURL = urlRoot + "/yonbip/scm/storeout/list"
var StoreOutDetailURL = urlRoot + "/yonbip/scm/storeout/detail"
var StoreInListURL = urlRoot + "/yonbip/scm/storein/list"
var StoreInDetailURL = urlRoot + "/yonbip/scm/storein/detail"
var StoreTransferListURL = urlRoot + "/yonbip/scm/storetransfer/list"
var LocationStockAnalysisList = urlRoot + "/yonbip/scm/locationstockanalysis/list"
var StockAnalysisList = urlRoot + "/yonbip/scm/stockanalysis/list"

// sd
var MerchantProductPriceURL = urlRoot + "/yonbip/sd/goods/price/customerproduct/list"
var VoucherOrderListURL = urlRoot + "/yonbip/sd/voucherorder/list"
var VoucherOrderDetailURL = urlRoot + "/yonbip/sd/voucherorder/detail"
var VoucherOrderSaveURL = urlRoot + "/yonbip/sd/voucherorder/save"
var VoucherOrderBatchAuditURL = urlRoot + "/yonbip/sd/voucherorder/batchaudit"
var VoucherOrderCloseURL = urlRoot + "/yonbip/sd/voucherorder/close"
var VoucherSaleReturnListURL = urlRoot + "/yonbip/sd/vouchersalereturn/list"
var VoucherSaleReturnDetailURL = urlRoot + "/yonbip/sd/vouchersalereturn/detail"
var VoucherDeliveryListURL = urlRoot + "/yonbip/sd/voucherdelivery/list"
var VoucherDeliveryUnauditURL = urlRoot + "/yonbip/sd/voucherdelivery/unaudit"
var VoucherDeliveryBatchDeleteURL = urlRoot + "/yonbip/sd/voucherdelivery/batchdelete"

// dst
var TradeVouchImportURL = urlRoot + "/yonbip/sd/dst/tradevouch/import"
var TradeVouchQueryURL = urlRoot + "/yonbip/sd/dst/tradevouch/query"
var SuitGoodsQueryURL = urlRoot + "/yonbip/sd/dst/suitgoods/query"
var TradeOrderQueryURL = urlRoot + "/yonbip/sd/dst/tradeorder/query"
var TradeOrderHoldURL = urlRoot + "/yonbip/sd/dst/tradeorder/tradehold"
